modLoader="javafml"
loaderVersion="[36,)"
license="GNU LGPL v2.1"

[[mods]]
	modId="herbacraft"
	version="1.0.0a"
	displayName="Herbacraft"
	credits="rizet and GitHub contributors"
	authors="rizet"
	description=''''''
	