modLoader="javafml"
loaderVersion="[36,)"
license="GNU LGPL v2.1"

[[mods]]
	modId="herbacraft"
	version="1.0.0-alpha"
	displayName="Herbacraft"
	credits="rizet, juanoginer"
	authors="rizet"
	description=''''''
	